package com.hospital.hms.entity;

public enum Department {
    ADMINISTRATION, CARDIOLOGY, NEUROLOGY, ORTHOPEDICS,
    PEDIATRICS, GYNECOLOGY, ONCOLOGY, RADIOLOGY,
    PHARMACY, LABORATORY, EMERGENCY, ICU, NURSING, HR, ACCOUNTS
}
