package com.hospital.hms.entity;

public enum Designation {
    CHIEF_MEDICAL_OFFICER, SENIOR_DOCTOR, JUNIOR_DOCTOR,
    HEAD_NURSE, STAFF_NURSE, RECEPTIONIST, PHARMACIST,
    LAB_TECHNICIAN, RADIOLOGIST, HR_MANAGER, ACCOUNTANT,
    ADMIN_STAFF, SECURITY, CLEANER
}
